config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  root "products#index"

  get 'dashboard/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :image, dependent: true
  enum gender: [:male, :female, :unisex]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy, :update]

  def index
    @products = Product.all
  end

  def show; end

  private

  def set_product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/about.html.erb
<h3>
  <li>Project start date 08.04.2021</li>
  <li>Name: Vadim</li>
  <li>About the website: Socks eshop. Free delivery. Discounts!</li>
</h3>

app/views/layouts/_navigation.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" <%= link_to 'Home', products_path, class: 'nav-link active' %></a>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <a class="nav-link" <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %></a>
    </li>
  <% else %>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></a>
    </li>
  <% end %>
  <li class="nav-item">
    <a class="nav-link" <%= link_to 'About us', dashboard_about_path, class: 'nav-link' %></a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "socks_eshop" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "socks_eshop" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </main>
  </body>
</html>

app/views/products/index.html.erb
<h3>All products:</h3>
<h4>
  <% @products.each do |t| %>
    <li><% if t.image.attached? %>
        <%= image_tag t.image.representation(resize: "100x100") %>
      <% else %>
        <strong><%= link_to "No image", product_path(t) %></strong>
        <% end %>
      <%= link_to t.title, product_path(t) %></li>
    <li><%= t.price %></li>
  <% end %></h4>

app/views/products/show.html.erb
<h4>Product name: <strong><%= @product.title %></strong></h4>
<h4>Description: <strong><%= @product.description %></strong></h4>
<h4>Category: <strong><%= @product.category %></strong></h4>
<h4>Gender: <strong><%= @product.gender %></strong></h4>
<h4>Size: <strong><%= @product.size %></strong></h4>
<% if @product.image.attached? %>
  <%= image_tag @product.image.representation(resize: "100x100") %>
<% else %>
  <strong>No image</strong>
<% end %>
<h4>Manufacturer: <strong><%= @product.manufacturer %></strong></h4>
<h4>Price: <strong><%= @product.price %></strong></h4>